remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Documentación

nombres: Zully Vega
submodulo: Lógica de Programación
periodo: 2023-2
url_foto: https://firebasestorage.googleapis.com/v0/b/fotos-f682a.appspot.com/o/Foto.JPG?alt=media&token=39ad9874-fdca-437d-a791-d4766fa10898&_gl=1*l5z2q*_ga*NTczMzc2OTc0LjE2OTY4ODA1MDY.*_ga_CW55HF8NVT*MTY5Njg4MDUwNS4xLjEuMTY5Njg4MDgzNS42MC4wLjA.